# ****************************************
# appveyor.yml - Appveyor CI configuration
# ****************************************
environment:
  matrix:
    # We only have a pre-compiled PyQt5 for Python 3.4, so only test on that.
    - PYTHON: "C:\\Python34"

install:
  # Add the correct Python to the path.
  - set PATH=%PYTHON%;%PYTHON%\Script;%PATH%
  # Install dependencies needed by the CI script and by Enki.
  - git clone https://github.com/hlamer/qutepart.git
  - python -m pip install -U -r qutepart\tests\ci\requirements.txt
  # Use a python script to do all the heavy lifting.
  - python tests\ci.py install

# Use this to prevent Appveyor from running MSBuild. See https://www.appveyor.com/docs/appveyor-yml
# line 181.
build_script:
  - echo "Avoiding the MSBUILD step."

# See https://www.appveyor.com/docs/appveyor-yml line 215.
test_script:
  - python tests\ci.py test

# See https://www.appveyor.com/docs/build-cache.
cache:
  - \downloads
